### ISSUE TITLE
Doesn't work on 10.12.3 (16D32)

### ISSUE THREAD

**Issue by krychevsk16** [ivanvza/arpy#14]
When I try to type with sudo, the program doesn't even start working, just goes back to main screen. Also **MANY ERRORS**:

1. 
```
[Info] Enabling IP Forwarding...
sysctl: unknown oid 'net.inet.ip.fw.enable'
```
The system doesn't even know the command

2.
```
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "arpy.py", line 145, in poison
    except KeyboardInterupt:
NameError: global name 'KeyboardInterupt' is not defined


Traceback (most recent call last):
  File "arpy.py", line 208, in <module>
    main()
  File "arpy.py", line 199, in main
    start_poisen(target, interface, filter_parser())
  File "arpy.py", line 169, in start_poisen
    pkt = scapy.sniff(iface=interface,filter=scapy_filter,prn=dnshandle)
  File "/Library/Python/2.7/site-packages/scapy/sendrecv.py", line 610, in sniff
    p = s.recv()
  File "/Library/Python/2.7/site-packages/scapy/arch/pcapdnet.py", line 441, in recv
    pkt = self.ins.next()
  File "/Library/Python/2.7/site-packages/scapy/arch/pcapdnet.py", line 390, in next
    s,us = h.getts()
AttributeError: 'NoneType' object has no attribute 'getts'

Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "arpy.py", line 145, in poison
    except KeyboardInterupt:
NameError: global name 'KeyboardInterupt' is not defined
```

I don't even understand any of this.

**Comment by onesentinel** [comment]
The Problem is that you need IP/Port Forwarding on your Mac. On OS previous to El Capitan Apple used the 'net.inet.ip.fw.enable' kernel variable. This doesn't exist anymore so the script tries to change the value with
" sysctl: unknown oid 'net.inet.ip.fw.enable' "
but can't.

So please someone update this to Sierra!!

**Comment by krychevsk16** [comment]
Meh, I already removed this and python stuff. There is no way for IP forwarding in Sierra so...rip the project.

**Comment by todaycoder001** [comment]
when i input "sudo python arpy.py -t 192.168.2.100 -g 255.255.255.0 -i en0 --sniff", then it shows sysctl: unknown oid 'net.inet.ip.fw.enable' why?

**Comment by awhipp** [comment]
On the latest versions of Mac you can enable port forwarding with `net.inet.ip.forwarding`

I have it setup in my fork of this branch.
